dist: xenial
language: python
matrix:
  include:
    - python: 3.6
      env: TOX_ENV=py36-django111-drf37
    - python: 3.6
      env: TOX_ENV=py36-django111-drf38
    - python: 3.6
      env: TOX_ENV=py36-django111-drf39
    - python: 3.6
      env: TOX_ENV=py36-django111-drf310
    - python: 3.6
      env: TOX_ENV=py36-django20-drf37
    - python: 3.6
      env: TOX_ENV=py36-django20-drf38
    - python: 3.6
      env: TOX_ENV=py36-django20-drf39
    - python: 3.6
      env: TOX_ENV=py36-django20-drf310
    - python: 3.6
      env: TOX_ENV=py36-django21-drf37
    - python: 3.6
      env: TOX_ENV=py36-django21-drf38
    - python: 3.6
      env: TOX_ENV=py36-django21-drf39
    - python: 3.6
      env: TOX_ENV=py36-django21-drf310
    - python: 3.6
      env: TOX_ENV=py36-django22-drf37
    - python: 3.6
      env: TOX_ENV=py36-django22-drf38
    - python: 3.6
      env: TOX_ENV=py36-django22-drf39
    - python: 3.6
      env: TOX_ENV=py36-django22-drf310
    - python: 3.7
      env: TOX_ENV=py37-django111-drf37
    - python: 3.7
      env: TOX_ENV=py37-django111-drf38
    - python: 3.7
      env: TOX_ENV=py37-django111-drf39
    - python: 3.7
      env: TOX_ENV=py37-django111-drf310
    - python: 3.7
      env: TOX_ENV=py37-django20-drf37
    - python: 3.7
      env: TOX_ENV=py37-django20-drf38
    - python: 3.7
      env: TOX_ENV=py37-django20-drf39
    - python: 3.7
      env: TOX_ENV=py37-django20-drf310
    - python: 3.7
      env: TOX_ENV=py37-django21-drf37
    - python: 3.7
      env: TOX_ENV=py37-django21-drf38
    - python: 3.7
      env: TOX_ENV=py37-django21-drf39
    - python: 3.7
      env: TOX_ENV=py37-django21-drf310
    - python: 3.7
      env: TOX_ENV=py37-django22-drf37
    - python: 3.7
      env: TOX_ENV=py37-django22-drf38
    - python: 3.7
      env: TOX_ENV=py37-django22-drf39
    - python: 3.7
      env: TOX_ENV=py37-django22-drf310
    - python: 3.8-dev
      env: TOX_ENV=py38-django111-drf37
    - python: 3.8-dev
      env: TOX_ENV=py38-django111-drf38
    - python: 3.8-dev
      env: TOX_ENV=py38-django111-drf39
    - python: 3.8-dev
      env: TOX_ENV=py38-django111-drf310
    - python: 3.8-dev
      env: TOX_ENV=py38-django20-drf37
    - python: 3.8-dev
      env: TOX_ENV=py38-django20-drf38
    - python: 3.8-dev
      env: TOX_ENV=py38-django20-drf39
    - python: 3.8-dev
      env: TOX_ENV=py38-django20-drf310
    - python: 3.8-dev
      env: TOX_ENV=py38-django21-drf37
    - python: 3.8-dev
      env: TOX_ENV=py38-django21-drf38
    - python: 3.8-dev
      env: TOX_ENV=py38-django21-drf39
    - python: 3.8-dev
      env: TOX_ENV=py38-django21-drf310
    - python: 3.8-dev
      env: TOX_ENV=py38-django22-drf37
    - python: 3.8-dev
      env: TOX_ENV=py38-django22-drf38
    - python: 3.8-dev
      env: TOX_ENV=py38-django22-drf39
    - python: 3.8-dev
      env: TOX_ENV=py38-django22-drf310
    - python: 3.7
      env: TOX_ENV=lint
    - python: 3.7
      env: TOX_ENV=readme
install:
 - pip install tox
script:
 - tox -e $TOX_ENV
